### ISSUE TITLE
Ground Truth Mesh Data

### ISSUE THREAD

**Issue by hanhung** [THU-LYJ-Lab/SS3DM-Exporter#7]
Hello,

Congratulations on your work! I was wondering if you will release the GT meshes (fbx or obj) for each map as well? Right now I only see the sensor data provided in the downloadable dataset.

Thanks

**Comment by YuePanEdward** [comment]
The GT meshes for Town 10 can be found in the baseline folder of `output_mesh_part`. The others seem not to have been uploaded yet.

**Comment by YuePanEdward** [comment]
However, after inspecting the GT data (on Town 10), it seems that there are some missalignments between the GT and baseline mesh. On sequence medium (600) and long (1000), there's a building on the top right corner of the map but the building was not captured by the baseline methods.
Besides, it seems that the LiDAR data and camera data have some missalignments on the short sequence  (200). Several buildings are presented in the camera image but do not appear in the LiDAR scan. I guess this may result from some version modification of the scene file.

**Comment by BlueNine9** [comment]
Thank you for your feedback. We have updated the GT mesh.
